openapi: 3.0.3
info:
  title: API gateway
  description: API gateway бэкенда
  version: 0.0.1
servers:
  - description: Local server
    url: http://localhost:8080/
  
paths: 
  /auth/sendVerifyCode:
    post:
      tags:
        - User
      summary: Отправить код на почту
      description: Отправить код верификации
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendVerifyCodeRequest"
      responses:
        200:
          description: успешно отправлен код

  /auth/signUp:
    post:
      tags:
        - User
      summary: Регистрация пользователя
      description: Регистрирует пользователя в системе
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpRequest"
      responses:
        201:
          description: Всё хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"

  /auth/access: 
    get:
      tags: 
        - User
      summary: Авторизация пользователя
      description: Авторизирует пользователя в системе
      responses:
        200:
          $ref: "#/components/responses/GetAccessTypeResponse"
        400:
          $ref: "#/components/responses/ErrorResponse"

  /categories:
    post:
      tags:
        - Product
      description: Добавить новую категорию
      summary: Добавить новую категорию
      security:
        - bearerAuth: [ "ADMIN", "MANAGER" ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCategoryRequest"
      responses:
        201:
          description: Всё хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"
    get:
      tags:
        - Category
      description: Получить список категорий
      summary: Получить список категорий
      parameters:
        - in: query
          name: type
          schema:
            type: string
            enum:
              - root
              - leaf
      responses:
        200: 
          description: Все хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"

  /categories/children/{categoryID}:
    get:
      tags:
        - Category
      description: Получить список подкатегорий
      summary: Получить список подкатегорий
      parameters:
        - $ref: "#/components/parameters/categoryID"
      responses:
        200: 
          description: всё хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"

  /categories/{categoryID}:
    get:
      tags:
        - Category
      description: Получить Категорию
      summary: Получить категорию
      parameters:
        - $ref: "#/components/parameters/categoryID"
      responses:
        200: 
          description: всё хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"

  /products:
    post:
      tags: 
        - Product
      description: Добавление товара
      summary: Добавление товара
      security:
        - bearerAuth: [ "ADMIN", "MANAGER" ]
      requestBody: 
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductRequest"
      responses:
        201:
          description: Всё хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"
    get:
      tags: 
        - Product
      description: Получить список товаров
      summary: Получить список товаров
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        200:
          description: Всё хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"

  /products/{productID}:
    get:
      tags:
        - Product
      description: Получение информации о товаре
      summary: Получение информации о товаре
      parameters:
        - $ref: "#/components/parameters/productID"
      responses:
        200:
          description: Всё хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"
    delete:
      tags:
        - Product
      description: Удаление товара
      summary: Удаление товара 
      security:
        - bearerAuth: [ "ADMIN", "MANAGER" ]
      parameters:
        - $ref: "#/components/parameters/productID"
      responses:
        204:
          description: Успешно
        400:
          $ref: "#/components/responses/ErrorResponse"

  /auth/signIn:
    post:
      tags:
        - User
      summary: Авторизация пользователя
      description: Авторизирует пользователя в системе
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInRequest"
      responses:
        201:
          description: всё хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"

  /auth/refreshToken:
    get:
      tags:
        - User
      summary: Обновление токена
      description: Обновление токена
      responses:
        200:
          description: все хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"

  /images:
    post:
      tags:
        - Image
      description: Загрузить фото
      summary: Загрузить фото
      security:
        - bearerAuth: [ "ADMIN", "MANAGER" ]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        201:
          description: Всё хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"

  /images/{imageID}:
    delete:
      tags: 
       - Image
      description: Загрузить фото
      summary: Загрузить фото
      parameters:
        - $ref: "#/components/parameters/imageID"
      responses:
        204:
          description: Все хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"

  /cart:  
    post:
      tags:
        - Shopping Cart
      description: Добавление товара в корзину
      summary: Добавление товара в корзину
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddProductToCartRequest"
      responses:
        201:
          description: Все хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"
    delete:
      tags:
        - Shopping Cart
      description: Очистка корзины
      summary: Очистка корзины
      responses:
        204:
          description: Все хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"
    get:
      tags:
        - Shopping Cart
      description: Получение корзины
      summary: Получение корзины
      responses:
        200:
          description: Все хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"

  /cart/{productID}:
    patch:
      tags:
        - Shopping Cart
      description: Обновление количества товара в корзине
      summary: Обновление количества товара в корзине
      parameters:
        - $ref: "#/components/parameters/productID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCartProductRequest"
      responses:
        200:
          description: Все хорошо
    delete:
      tags:
        - Shopping Cart
      description: Добавление товара в корзину
      summary: Добавление товара в корзину
      parameters:
        - $ref: "#/components/parameters/productID"
      responses:
        204:
          description: Все хорошо

components:
  schemas:
    CreateProductRequest:
      type: object
      required: 
        - id
        - name
        - description
        - price
        - categoryName
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        photoUrl:
          type: string
        price:
          type: number
          format: double
        categoryName:
          type: string

    CreateCategoryRequest:
      type: object
      required:
        - id
        - name
      properties:
        id: 
          type: string
          format: uuid
        name:
          type: string
        photoUrl: 
          type: string
        parent:
          type: string

    SendVerifyCodeRequest:
      required:
        - email
      properties:
        email:
          type: string

    SignInRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
        
    SignUpRequest:
      type: object
      required:
        - email
        - firstName
        - lastName
        - password
        - code
      properties:
        email:
          type: string
        firstName:  
          type: string
        lastName: 
          type: string
        password:
          type: string
        code:
          type: integer

    GetAccessTypeResponse:
      type: object
      required:
        - accessType
      properties:
        accessType:
          type: string
          enum:
            - ADMIN
            - MANAGER
            - CUSTOMER

    AddProductToCartRequest:
      type: object
      required:
        - name
        - productID
        - photoUrl
        - price
      properties:
        name:
          type: string
        productID:
          type: string
          format: uuid
        price:
          type: number
          format: double
        photoUrl:
          type: string

    UpdateCartProductRequest:
      type: object
      required:
        - quantity
      properties:
        quantity:
          type: integer

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string

  responses:
    GetAccessTypeResponse:
      description: Все хорошо
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GetAccessTypeResponse"

    ErrorResponse:
      description: Что-то не так
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

  parameters:
    productID:
      name: productID
      in: path
      required: true
      schema:
        type: string
        format: uuid
    categoryID:
      name: categoryID
      in: path
      required: true
      schema:
        type: string
        format: uuid
    imageID:
      name: imageID
      in: path
      required: true
      schema:
        type: string
        format: uuid