version: '3.9'
volumes:
  postgres_data:
  redis_data:

services:
  yukiko_db:
    container_name: yukiko_db
    image: postgres:11.13-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-yukiko_db}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT:-5432}:5432
    networks:
      app_network:
        ipv4_address: 171.4.4.11
        aliases:
          - yukiko.postgres.loc

  redis:
    container_name: yukiko-redis
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD:-password}
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT:-6379}:6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_URL=redis://yukiko.redis.loc:6379
      - "REDIS_PASSWORD:${REDIS_PASSWORD:-password}"
    networks:
      app_network:
        ipv4_address: 171.4.4.9
        aliases:
          - yukiko.redis.loc

  auth:
    container_name: auth
    depends_on:
      - yukiko_db
    build:
      context: .
      dockerfile: ./docker/auth.dockerfile
    env_file:
      - .env
    ports:
      - ${AUTH_HTTP_PORT:-8081}:8081
    networks:
      app_network:
        ipv4_address: 171.4.4.12
        aliases:
          - yukiko.auth.loc

  product:
    container_name: product
    depends_on:
      - yukiko_db
    build:
      context: .
      dockerfile: ./docker/product.dockerfile
    env_file:
      - .env
    ports:
      - ${PRODUCT_HTTP_PORT:-8082}:8082
    networks:
      app_network:
        ipv4_address: 171.4.4.13
        aliases:
          - yukiko.product.loc

  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./docker/gateway.dockerfile
    env_file:
      - .env
    ports:
      - ${GATEWAY_HTTP_PORT:-8080}:8080
    networks:
      app_network:
        ipv4_address: 171.4.4.10
        aliases:
          - yukiko.gateway.loc


networks:
  app_network:
    name: app_network
    ipam:
      config:
        - subnet: "171.4.4.0/24"