openapi: 3.0.3
info:
  title: Shopping Cart Service 
  description: Сервис корзины товаров
  version: 0.0.1
servers:
  - description: Local server
    url: http://localhost:8084/

paths:
  /cart:  
    post:
      tags:
        - Shopping Cart
      description: Добавление товара в корзину
      summary: Добавление товара в корзину
      parameters:
        - in: query
          required: true
          name: user
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddProductToCartRequest"
      responses:
        201:
          description: Все хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"
    delete:
      tags:
        - Shopping Cart
      description: Очистка корзины
      summary: Очистка корзины
      parameters:
        - in: query
          required: true
          name: user
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Все хорошо
        400:
          $ref: "#/components/responses/ErrorResponse"
    get:
      tags:
        - Shopping Cart
      description: Получение корзины
      summary: Получение корзины
      parameters:
        - in: query
          required: true
          name: user
          schema:
            type: string
            format: uuid
      responses:
        200:
          $ref: "#/components/responses/GetCartResponse"
        400:
          $ref: "#/components/responses/ErrorResponse"

  /cart/{productID}:
    patch:
      tags:
        - Shopping Cart
      description: Обновление количества товара в корзине
      summary: Обновление количества товара в корзине
      parameters:
        - $ref: "#/components/parameters/productID"
        - in: query
          required: true
          name: user
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCartProductRequest"
      responses:
        200:
          description: Все хорошо
    delete:
      tags:
        - Shopping Cart
      description: Добавление товара в корзину
      summary: Добавление товара в корзину
      parameters:
        - $ref: "#/components/parameters/productID"
        - in: query
          required: true
          name: user
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Все хорошо

components:
  schemas:  
    Product:
      required:
        - id
        - productID
        - customerID
        - name
        - price
        - quantity
        - photoUrl
      properties:
        id:
          type: string
          format: uuid
        productID:
          type: string
          format: uuid
        customerID:
          type: string
          format: uuid
        name:
          type: string
        photoUrl:
          type: string
        price:
          type: number
          format: double
        quantity:
          type: integer

    Cart:
      required:
        - products
        - totalPrice
      properties:
        products:
          type: array
          items:
            $ref: "#/components/schemas/Product"
        totalPrice:
          type: number
          format: double
  
    AddProductToCartRequest:
      type: object
      required:
        - name
        - productID
        - photoUrl
        - price
      properties:
        name:
          type: string
        productID:
          type: string
          format: uuid
        price:
          type: number
          format: double
        photoUrl:
          type: string

    UpdateCartProductRequest:
      type: object
      required:
        - quantity
      properties:
        quantity:
          type: integer

    GetCartResponse:
      type: object
      required:
        - products
        - totalPrice
      properties:
        products:
          type: array
          items:
            $ref: "#/components/schemas/Product"
        totalPrice:
          type: number
          format: double

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string

  responses:
    GetCartResponse:
      description: Что-то не так
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GetCartResponse"

    ErrorResponse:
      description: Что-то не так
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    
  parameters:
    productID:
      name: productID
      in: path
      required: true
      schema:
        type: string
        format: uuid
