// Code generated by entc, DO NOT EDIT.

package category

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the category type in the database.
	Label = "category"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// EdgeParentCategory holds the string denoting the parentcategory edge name in mutations.
	EdgeParentCategory = "parentCategory"
	// EdgeChildrenCategories holds the string denoting the childrencategories edge name in mutations.
	EdgeChildrenCategories = "childrenCategories"
	// EdgeProducts holds the string denoting the products edge name in mutations.
	EdgeProducts = "products"
	// Table holds the table name of the category in the database.
	Table = "categories"
	// ParentCategoryTable is the table that holds the parentCategory relation/edge.
	ParentCategoryTable = "categories"
	// ParentCategoryColumn is the table column denoting the parentCategory relation/edge.
	ParentCategoryColumn = "category_id"
	// ChildrenCategoriesTable is the table that holds the childrenCategories relation/edge.
	ChildrenCategoriesTable = "categories"
	// ChildrenCategoriesColumn is the table column denoting the childrenCategories relation/edge.
	ChildrenCategoriesColumn = "category_id"
	// ProductsTable is the table that holds the products relation/edge.
	ProductsTable = "products"
	// ProductsInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	ProductsInverseTable = "products"
	// ProductsColumn is the table column denoting the products relation/edge.
	ProductsColumn = "category_id"
)

// Columns holds all SQL columns for category fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCategoryID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
