// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CartProduct is the predicate function for cartproduct builders.
type CartProduct func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
